---
- name: "Create Open Data Hub subscription"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'open-data-hub/subscription.yml.j2') }}"
  vars:
    namespace: openshift-operators

- name: "Wait for Open Data Hub CRD's to exist"
  k8s_facts:
    api_version: "apiextensions.k8s.io/v1beta1"
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop: "{{ och_expected_crds }}"
  register: crds
  until: crds.resources|length > 0
  retries: 30
  delay: 10

- name: Open Data Hub Subscription tasks complete
  debug:
    msg: "Open Data Hub Subscription completed successfully."
  when: not silent|bool
